### ISSUE TITLE
Installer Corrupt

### ISSUE THREAD

**Issue by berlamont** [gmasterscm/tour#1]
Can't run the installer as Windows says it is corrupt.
Here's the link that I was directed to from the email announcement.
https://gmaster.io/Installer

**Comment by psantosl** [comment]
Hi @berlamont!
The URL is correct. I just clicked, downloaded it and it runs correctly.
Mine is a Windows 10. What's yours?

**Comment by berlamont** [comment]
Windows 10 as well, weird I try it through Edge as Chrome and FF are doing that.

**Comment by DustinTheDev** [comment]
Try putting the installer file in a different location (e.g. c:\temp\). Moving it from my default download folder corrected the issue.

**Comment by berlamont** [comment]
Looks like it's working now, thanks!
